redis:
  image: redis
  ports:
    - "6379"
web:
  build: .
  command: bundle exec ruby app.rb -o 0.0.0.0
  volumes:
    - .:/myapp
  ports:
    - "14567:4567"
  links:
    - redis
  environment:
    - REDIS_HOST=redis